debug: false

# Changing these values requires a restart

# How many seconds between backups
backup-duration: 600
# How many seconds until the first backup after a reboot
initial-backup-duration: 600

# Placeholders are {player}, {player_uuid}, {world}
rewards:
  - "cc give p dailyrewardcrate 5 {player}"

community-rewards-enabled: false

reward-message: "Great work! You hit today’s daily-reward goal! Thanks for making Theatria awesome!"

# Placeholders are {player}, {player_uuid}, {world}, {streak}
# no rewards for streaks less than 2
streak-rewards:
  2:
  - "cc give p dailyrewardcrate 1 {player}"
  3:
  - "cc give p dailyrewardcrate 2 {player}"
  7:
  - "cc give p dailyrewardcrate 3 {player}"
  14:
  - "cc give p dailyrewardcrate 5 {player}"
  30:
  - "cc give p dailyrewardcrate 10 {player}"