debug: false

# Changing these values requires a restart

# How many seconds between backups
backup-duration: 600
# How many seconds until the first backup after a reboot
initial-backup-duration: 600

# Placeholders are {player}, {player_uuid}, {world}
rewards:
  - "cc give p sessioncrate 5 {player}"