name: TheatriaSessions
version: ${version}
main: com.playtheatria.sessions.TheatriaSessions
api-version: '1.21'
general-utils-version: ${generalUtilsVersion}
theatria-time-version: ${theatriaTimeVersion}
depend: [Essentials, TheatriaTime]
commands:
  session:
    usage: /<command>
  activity:
    usage: /<command>
  streaks:
    usage: /<command>
  community:
    usage: /<command>