name: Deploy via Pterodactyl API
on:
  pull_request:
    branches:
      - stage
    
permissions:
  contents: read
  packages: read

jobs:
  build-deploy-restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: which jq || echo "jq not found"
      - run: ./gradlew shadowJar --no-daemon
        env:
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get signed upload URL
        id: sign
        run: |
          echo "DIR='${{ secrets.TARGET_DIR }}'"
          RESP=$(curl -v -s \
             -H "Authorization: Bearer ${{ secrets.PTERO_TOKEN }}" \
             -H "Accept: application/json" \
             "${{ secrets.PTERO_PANEL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/files/upload?directory=${{ secrets.TARGET_DIR }}")
          echo "RESPONSE:"
          echo "$RESP"
      - name: Upload JAR to signed URL
        run: |
          FILE=$(ls build/libs/TheatriaSessions.jar | head -n1)
          curl -s -X PUT -T "$FILE" "${{ steps.sign.outputs.url }}&filename=$(basename "$FILE")"
      - name: Restart server
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.PTERO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"signal":"restart"}' \
            "${{ secrets.PTERO_PANEL }}/api/client/servers/${{ secrets.PTERO_SERVER_ID }}/power"